# If this option is enabled, the player who killed another player will be given the head of the killed one.
EnableDropPlayerHeads: true
# Chanse for dropping head after player kill.
DropPlayerHeadChance: 100